name: "Discord"

on:
  schedule:
    - cron: "0 0 * * *"
    # - cron: "00 01,13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Package Installer
        run: |
          sudo snap install ipsw
      - name: Run ipsw watch WebKit/WebKit
        run: |
          /snap/bin/ipsw watch --pattern '(?i)Lockdown Mode' --days 1 --api ${{ secrets.GITHUB_TOKEN }} --discord-id ${{ secrets.DISCORD_ID }} --discord-token ${{ secrets.DISCORD_TOKEN }} WebKit/WebKit
