name: "Discord"

on:
  schedule:
    - cron: "0 */1 * * *" # every 1 hour
    # - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Tags
        id: cache-tags
        uses: actions/cache@v4
        with:
          path: watch-cache
          key: ${{ runner.os }}-watch-cache
      - name: Package Installer
        run: |
          sudo snap install ipsw
      - name: Check Cache
        run: |
          cat watch-cache || echo "No cache found"
      - name: Run ipsw watch WebKit/WebKit
        run: |
          /snap/bin/ipsw watch WebKit/WebKit --pattern '(?i)Lockdown Mode' --days 1 --cache watch-cache \
          --api ${{ secrets.GITHUB_TOKEN }} \
          --discord \
          --discord-id ${{ secrets.DISCORD_ID }} \
          --discord-token ${{ secrets.DISCORD_TOKEN }} \
          --discord-icon "https://raw.githubusercontent.com/blacktop/ipsw/master/www/static/img/webkit.png"
      - name: Run ipsw watch apple-oss-distributions/distribution-macOS
        run: |
          /snap/bin/ipsw watch apple-oss-distributions/distribution-macOS --tags --cache watch-cache \
          --api ${{ secrets.GITHUB_TOKEN }} \
          --discord \
          --discord-id ${{ secrets.DISCORD_ID }} \
          --discord-token ${{ secrets.DISCORD_TOKEN }} \
          --discord-icon "https://avatars.githubusercontent.com/u/91919287" \
          --mastodon \
          --mastodon-client-id ${{ secrets.MASTODON_CLIENT_ID }} \
          --mastodon-client-secret ${{ secrets.MASTODON_CLIENT_SECRET }} \
          --mastodon-access-token ${{ secrets.MASTODON_ACCESS_TOKEN }}